export const initialBooks = [
  {
    id: 1,
    title: "The Hunger Games",
    author: "Suzanne Collins",
    genre: "Fantasy",
    status: "reading",
    pages: 374,
    currentPage: 220,
    rating: 4.8,
  },
  {
    id: 2,
    title: "The Midnight Library",
    author: "Matt Haig",
    genre: "Drama",
    status: "wantToRead",
    pages: 304,
    currentPage: 0,
    rating: 4.7,
  },
  {
    id: 3,
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    genre: "Fantasy",
    status: "completed",
    pages: 332,
    currentPage: 332,
    rating: 4.9,
  },
  {
    id: 4,
    title: "Dune",
    author: "Frank Herbert",
    genre: "Sci-Fi",
    status: "wantToRead",
    pages: 688,
    currentPage: 0,
    rating: 4.8,
  },
  {
    id: 5,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    status: "completed",
    pages: 432,
    currentPage: 432,
    rating: 4.6,
  },
  {
    id: 6,
    title: "The Fault in Our Stars",
    author: "John Green",
    genre: "Drama",
    status: "reading",
    pages: 313,
    currentPage: 97,
    rating: 4.5,
  },
  {
    id: 7,
    title: "Percy Jackson: The Lightning Thief",
    author: "Rick Riordan",
    genre: "Fantasy",
    status: "wantToRead",
    pages: 377,
    currentPage: 0,
    rating: 4.7,
  },
  {
    id: 8,
    title: "1984",
    author: "George Orwell",
    genre: "Dystopia",
    status: "completed",
    pages: 328,
    currentPage: 328,
    rating: 4.8,
  },
  {
    id: 9,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    status: "wantToRead",
    pages: 310,
    currentPage: 0,
    rating: 4.9,
  },
  {
    id: 10,
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    genre: "Drama",
    status: "completed",
    pages: 400,
    currentPage: 400,
    rating: 4.7,
  },
  {
    id: 11,
    title: "Project Hail Mary",
    author: "Andy Weir",
    genre: "Sci-Fi",
    status: "wantToRead",
    pages: 496,
    currentPage: 0,
    rating: 4.9,
  },
  {
    id: 12,
    title: "Little Women",
    author: "Louisa May Alcott",
    genre: "Drama",
    status: "completed",
    pages: 449,
    currentPage: 449,
    rating: 4.5,
  },
];
